export type InterfaceTextItem = { key: string; group: string; label: string; defaultValue: string };
export const interfaceTextCatalog: InterfaceTextItem[] = [
  ["ui.brand.name","品牌与导航","公司名称","双龙装饰"], ["ui.brand.product","品牌与导航","系统名称","AI 经营管理中心"],
  ["ui.nav.owner","品牌与导航","老板首页","老板首页"], ["ui.nav.projects","品牌与导航","工地管理","工地管理"],
  ["ui.nav.materials","品牌与导航","主材采购","主材采购"], ["ui.nav.customers","品牌与导航","客户销售","客户销售"],
  ["ui.nav.quotations","品牌与导航","设计报价","设计报价"], ["ui.nav.finance","品牌与导航","财务中心","财务中心"],
  ["ui.nav.inventory","品牌与导航","库存管理","库存管理"], ["ui.nav.schedule","品牌与导航","员工排班","员工排班"],
  ["ui.nav.agents","品牌与导航","Agent 中心","Agent 中心"], ["ui.nav.review","品牌与导航","AI 待确认","AI 待确认"],
  ["ui.nav.tasks","品牌与导航","最近待办","最近待办"], ["ui.nav.alerts","品牌与导航","老板要情","老板要情"],
  ["ui.nav.settings","品牌与导航","系统设置","系统设置"], ["ui.shell.assistant_online","品牌与导航","助手状态","AI 助手在线"],
  ["ui.shell.assistant_note","品牌与导航","助手说明","仅生成候选建议"], ["ui.shell.protected","品牌与导航","权限状态","权限保护"],
  ["ui.projects.list","工地管理","工地列表","工地列表"], ["ui.projects.flow","工地管理","施工流程","整体施工流程"],
  ["ui.projects.current","工地管理","当前施工","当前施工"], ["ui.projects.next","工地管理","下一步","下一步"],
  ["ui.projects.status","工地管理","工期状态","工期状态"], ["ui.customers.list","客户销售","客户列表","客户销售列表"],
  ["ui.customers.total","客户销售","客户总数","客户总数"], ["ui.customers.opportunity","客户销售","成交机会","成交机会"],
  ["ui.customers.followup","客户销售","下次跟进","下次跟进"], ["ui.review.category","AI 与审核","归属模块","归属模块"],
  ["ui.review.type","AI 与审核","事件类型","事件类型"], ["ui.review.manual","AI 与审核","自定义录入","自定义录入"],
  ["ui.review.import","AI 与审核","表格导入","表格导入"], ["ui.common.save","通用操作","保存","保存"],
  ["ui.common.saving","通用操作","保存中","保存中…"], ["ui.common.cancel","通用操作","取消编辑","取消编辑"],
  ["ui.common.close","通用操作","关闭","关闭"], ["ui.common.edit","通用操作","管理员编辑","管理员编辑"],
  ["ui.common.confirmed","通用状态","已确认","已确认"], ["ui.common.pending","通用状态","待确认","待确认"],
  ["ui.common.unassigned","通用状态","待分配","待分配"], ["ui.common.normal","通用状态","按计划","按计划"],
  ["ui.common.delayed","通用状态","延期","延期"],
].map(([key,group,label,defaultValue]) => ({ key, group, label, defaultValue }));
