import { useEffect, useMemo, useState } from "react";
import type { User } from "../auth/AuthProvider";
import { useInterfaceTexts } from "./InterfaceTextProvider";
import { interfaceTextCatalog } from "./interfaceText";
import "./settings.css";
import "./text-settings.css";
const roleLabels={owner:"老板",management:"内部管理层",employee:"普通员工"};
function TextSettings(){const{values,setValues,loading}=useInterfaceTexts();const[draft,setDraft]=useState<Record<string,string>>({});const[query,setQuery]=useState("");const[message,setMessage]=useState("");const[saving,setSaving]=useState(false);useEffect(()=>setDraft(values),[values]);const items=useMemo(()=>interfaceTextCatalog.filter(item=>`${item.group}${item.label}${item.defaultValue}`.toLowerCase().includes(query.toLowerCase())),[query]);async function save(){setSaving(true);setMessage("");const changed=Object.fromEntries(interfaceTextCatalog.flatMap(item=>{const value=(draft[item.key]??item.defaultValue).trim();return value!==item.defaultValue?[[item.key,value]]:[]}));const response=await fetch("/api/settings/texts",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({values:changed})});if(response.ok){const next=(await response.json()).values??{};setValues(next);setDraft(next);setMessage("文案已保存，所有账号刷新后生效")}else setMessage((await response.json()).error??"保存失败");setSaving(false)}if(loading)return <p>正在加载文案设置…</p>;let lastGroup="";return <section className="text-settings"><div className="text-settings__head"><div><span>INTERFACE CONTENT</span><h2>界面文案</h2><p>修改页面名称、栏目标题、按钮和状态文字，恢复默认后不再保存自定义值。</p></div><button type="button" onClick={()=>void save()} disabled={saving}>{saving?"保存中…":"保存全部文案"}</button></div><input className="text-settings__search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索页面、栏目或原文字"/><div className="text-settings__list">{items.map(item=>{const showGroup=item.group!==lastGroup;lastGroup=item.group;return <div className="text-setting" key={item.key}>{showGroup?<h3>{item.group}</h3>:null}<label><span>{item.label}<small>原文：{item.defaultValue}</small></span><input maxLength={500} value={draft[item.key]??item.defaultValue} onChange={e=>setDraft(current=>({...current,[item.key]:e.target.value}))}/><button type="button" onClick={()=>setDraft(current=>{const next={...current};delete next[item.key];return next})}>恢复默认</button></label></div>})}</div>{message?<p className="settings-message">{message}</p>:null}</section>}
export function UserManagementPage(){const[users,setUsers]=useState<User[]>([]);const[phone,setPhone]=useState("");const[password,setPassword]=useState("");const[role,setRole]=useState<"management"|"employee">("employee");const[message,setMessage]=useState("");async function load(){const r=await fetch("/api/auth/users");if(r.ok)setUsers((await r.json()).items)}useEffect(()=>{void load()},[]);return <div className="settings-page"><TextSettings/><section className="user-settings"><header><span>ACCESS CONTROL</span><h2>账号与权限</h2><p>老板创建账号；所有新账号首次登录必须修改临时密码。</p></header><form onSubmit={async e=>{e.preventDefault();setMessage("");const r=await fetch("/api/auth/users",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({phone,password,role})});if(!r.ok){setMessage((await r.json()).error??"创建失败");return}setPhone("");setPassword("");setMessage("账号已创建");await load()}}><label>手机号<input inputMode="numeric" value={phone} onChange={e=>setPhone(e.target.value)}/></label><label>临时密码<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="至少 12 位"/></label><label>角色<select value={role} onChange={e=>setRole(e.target.value as typeof role)}><option value="employee">普通员工</option><option value="management">内部管理层</option></select></label><button>创建账号</button>{message&&<p>{message}</p>}</form><div className="user-list">{users.map(user=><article key={user.id}><strong>{user.phone.replace(/(\d{3})\d{4}(\d{4})/,"$1****$2")}</strong><span>{roleLabels[user.role]}</span><small>{user.mustChangePassword?"等待首次改密":"已启用"}</small></article>)}</div></section></div>}
