import { randomUUID } from "node:crypto";
import type { Pool, PoolClient } from "pg";
import type { AgentCandidate, AuthUser, CandidateModule, ManagementStore } from "./types";

function candidate(row: any): AgentCandidate { return { id: row.id, module: row.target_module, kind: row.kind, payload: row.payload, confidence: Number(row.confidence), status: row.status, version: row.version, createdAt: new Date(row.created_at).toISOString() }; }

export class PostgresManagementStore implements ManagementStore {
  constructor(private readonly pool: Pool) {}
  async initialize(): Promise<void> { await this.pool.query(`
    CREATE TABLE IF NOT EXISTS management_users (id uuid PRIMARY KEY, phone text UNIQUE NOT NULL, password_hash text NOT NULL, role text NOT NULL CHECK(role IN ('owner','management','employee')), must_change_password boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now());
    CREATE TABLE IF NOT EXISTS management_sessions (token_hash text PRIMARY KEY, user_id uuid NOT NULL REFERENCES management_users(id) ON DELETE CASCADE, expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
    CREATE TABLE IF NOT EXISTS agent_candidates (id uuid PRIMARY KEY, source_key text UNIQUE NOT NULL, target_module text NOT NULL CHECK(target_module IN ('projects','procurement','crm')), kind text NOT NULL, payload jsonb NOT NULL, confidence numeric(4,3) NOT NULL, status text NOT NULL DEFAULT 'pending_review', version integer NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), reviewed_at timestamptz);
    CREATE TABLE IF NOT EXISTS module_records (id uuid PRIMARY KEY, candidate_id uuid UNIQUE NOT NULL REFERENCES agent_candidates(id), target_module text NOT NULL, kind text NOT NULL, payload jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
    CREATE TABLE IF NOT EXISTS review_decisions (id uuid PRIMARY KEY, candidate_id uuid NOT NULL REFERENCES agent_candidates(id), actor_id uuid NOT NULL REFERENCES management_users(id), decision text NOT NULL, reason text, payload jsonb, idempotency_key text UNIQUE, created_at timestamptz NOT NULL DEFAULT now());
    CREATE TABLE IF NOT EXISTS audit_entries (id uuid PRIMARY KEY, actor_id uuid, action text NOT NULL, object_type text NOT NULL, object_id text NOT NULL, details jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL DEFAULT now());
    CREATE INDEX IF NOT EXISTS idx_agent_candidates_status_created ON agent_candidates(status, created_at DESC);
    ALTER TABLE management_users DROP CONSTRAINT IF EXISTS management_users_role_check;
    ALTER TABLE management_users ADD CONSTRAINT management_users_role_check CHECK(role IN ('owner','management','employee'));
    DELETE FROM management_sessions WHERE expires_at <= now();
  `); }
  async bootstrapOwner(phone: string, passwordHash: string): Promise<void> { await this.pool.query(`INSERT INTO management_users(id,phone,password_hash,role) VALUES($1,$2,$3,'owner') ON CONFLICT(phone) DO NOTHING`, [randomUUID(), phone, passwordHash]); }
  async createUser(phone:string,passwordHash:string,role:"management"|"employee"){const r=await this.pool.query(`INSERT INTO management_users(id,phone,password_hash,role) VALUES($1,$2,$3,$4) RETURNING id,phone,role,must_change_password`,[randomUUID(),phone,passwordHash,role]);const x=r.rows[0];return{id:x.id,phone:x.phone,role:x.role,mustChangePassword:x.must_change_password};}
  async listUsers(){const r=await this.pool.query(`SELECT id,phone,role,must_change_password FROM management_users ORDER BY created_at`);return r.rows.map(x=>({id:x.id,phone:x.phone,role:x.role,mustChangePassword:x.must_change_password}));}
  async findUserByPhone(phone: string) { const r = await this.pool.query(`SELECT id,phone,password_hash,role,must_change_password FROM management_users WHERE phone=$1`,[phone]); const x=r.rows[0]; return x ? {id:x.id,phone:x.phone,passwordHash:x.password_hash,role:x.role,mustChangePassword:x.must_change_password}:null; }
  async createSession(userId:string, hash:string, expires:Date){ await this.pool.query(`INSERT INTO management_sessions(token_hash,user_id,expires_at) VALUES($1,$2,$3)`,[hash,userId,expires]); }
  async findSession(hash:string):Promise<AuthUser|null>{ const r=await this.pool.query(`SELECT u.id,u.phone,u.role,u.must_change_password FROM management_sessions s JOIN management_users u ON u.id=s.user_id WHERE s.token_hash=$1 AND s.expires_at>now()`,[hash]); const x=r.rows[0]; return x?{id:x.id,phone:x.phone,role:x.role,mustChangePassword:x.must_change_password}:null; }
  async deleteSession(hash:string){ await this.pool.query(`DELETE FROM management_sessions WHERE token_hash=$1`,[hash]); }
  async changePassword(userId:string,passwordHash:string){ await this.pool.query(`UPDATE management_users SET password_hash=$2,must_change_password=false WHERE id=$1`,[userId,passwordHash]); }
  async createCandidate(input:Omit<AgentCandidate,"id"|"status"|"version"|"createdAt">, sourceKey:string){ const r=await this.pool.query(`INSERT INTO agent_candidates(id,source_key,target_module,kind,payload,confidence) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(source_key) DO UPDATE SET source_key=excluded.source_key RETURNING *`,[randomUUID(),sourceKey,input.module,input.kind,input.payload,input.confidence]); return candidate(r.rows[0]); }
  async listCandidates(){ const r=await this.pool.query(`SELECT * FROM agent_candidates WHERE status='pending_review' ORDER BY created_at DESC`); return r.rows.map(candidate); }
  async confirmCandidate(id:string,version:number,key:string,actorId:string,payload?:Record<string,unknown>){ return this.transaction(async c=>{ const r=await c.query(`SELECT * FROM agent_candidates WHERE id=$1 FOR UPDATE`,[id]); const x=r.rows[0]; if(!x||x.status!=="pending_review"||x.version!==version) throw new Error("候选状态或版本已变化"); const finalPayload=payload??x.payload; await c.query(`INSERT INTO review_decisions(id,candidate_id,actor_id,decision,payload,idempotency_key) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(idempotency_key) DO NOTHING`,[randomUUID(),id,actorId,payload?"edited_and_confirmed":"confirmed",finalPayload,key]); await c.query(`INSERT INTO module_records(id,candidate_id,target_module,kind,payload) VALUES($1,$2,$3,$4,$5) ON CONFLICT(candidate_id) DO NOTHING`,[randomUUID(),id,x.target_module,x.kind,finalPayload]); const u=await c.query(`UPDATE agent_candidates SET status='projected',version=version+1,reviewed_at=now() WHERE id=$1 RETURNING *`,[id]); await c.query(`INSERT INTO audit_entries(id,actor_id,action,object_type,object_id,details) VALUES($1,$2,'candidate.projected','agent_candidate',$3,$4)`,[randomUUID(),actorId,id,{module:x.target_module,kind:x.kind}]); return candidate(u.rows[0]); }); }
  async rejectCandidate(id:string,version:number,actorId:string,reason:string){ return this.transaction(async c=>{ const u=await c.query(`UPDATE agent_candidates SET status='rejected',version=version+1,reviewed_at=now() WHERE id=$1 AND version=$2 AND status='pending_review' RETURNING *`,[id,version]); if(!u.rows[0]) throw new Error("候选状态或版本已变化"); await c.query(`INSERT INTO review_decisions(id,candidate_id,actor_id,decision,reason) VALUES($1,$2,$3,'rejected',$4)`,[randomUUID(),id,actorId,reason]); return candidate(u.rows[0]); }); }
  async listModuleRecords(module:CandidateModule){ const r=await this.pool.query(`SELECT id,candidate_id,kind,payload,created_at FROM module_records WHERE target_module=$1 ORDER BY created_at DESC`,[module]); return r.rows; }
  private async transaction<T>(fn:(c:PoolClient)=>Promise<T>):Promise<T>{ const c=await this.pool.connect(); try{await c.query("BEGIN");const v=await fn(c);await c.query("COMMIT");return v;}catch(e){await c.query("ROLLBACK");throw e;}finally{c.release();} }
}
